spring.application.name=flyway-migrations

# PostgreSQL setup
spring.datasource.url=jdbc:postgresql://localhost:5432/flyway_gr2
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate setup
# validimi i modelit ne krahasim me tabelen ne DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# konfigurimi i custom path per swagger
springdoc.swagger-ui.path=/docs

# JWT configuration
spring.jwt.secret=0aa446e418c8b22404e264fe91da3b57cbbb8d6c476a68653b9f915fa97d9461
# 24h in milliseconds
spring.jwt.expiration=86400000