spring.application.name=flyway-migrations

# PostgreSQL setup
spring.datasource.url=jdbc:postgresql://localhost:5432/flyway_gr2
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate setup
# validimi i modelit ne krahasim me tabelen ne DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true