CREATE TABLE departments
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(100)                             NOT NULL,
    location VARCHAR(100),
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employee_missions
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id INTEGER,
    mission_id  INTEGER,
    role        VARCHAR(50),
    CONSTRAINT pk_employee_missions PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(50)                              NOT NULL,
    last_name     VARCHAR(50)                              NOT NULL,
    department_id INTEGER,
    hire_date     date,
    email         VARCHAR(100),
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE missions
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                             NOT NULL,
    start_date  date,
    end_date    date,
    description VARCHAR(255),
    CONSTRAINT pk_missions PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE employee_missions
    ADD CONSTRAINT FK_EMPLOYEE_MISSIONS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_missions
    ADD CONSTRAINT FK_EMPLOYEE_MISSIONS_ON_MISSION FOREIGN KEY (mission_id) REFERENCES missions (id);